version: "3.8"
services:
  db:
    image: postgres:13.7
    container_name: local_postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - local_postgres:/var/lib/postgresql/data
  web:
    image: ${WEB_IMAGE}
    depends_on: [db]
    container_name: web
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: "db"
    restart: on-failure
    
  nginx:
    image: nginx
    depends_on: [web]
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  local_postgres:        



